import datetime
import sys
import math

def main():

    # Get the ADC_sample_rate from the user.
    if len(sys.argv) > 1:
        ADC_sample_rate = int(sys.argv[1])
    else:
        print("usage: py setTimer2.py <ADC_sample_rate>")
        return
    print("ADC_sample_rate: ", ADC_sample_rate)
    timer_reload_value = math.floor(11_059_200 / ADC_sample_rate - 256)

    rcap2h = (timer_reload_value >> 8) & 0xFF
    rcap2l = timer_reload_value & 0x00FF


    with open("SetTimer2_ADC_DAC.c", "w") as f1:
        f1.write('#include "aduc841.h"\n'
                '#include "SetTimer2_ADC_DAC.h"\n\n')
        f1.write(
            "/* This code generated by setTimer2.py\n"
            f"   on {datetime.datetime.now()}\n"
            f"   ADC_sample_rate target {ADC_sample_rate} \n"
            "Name: Matan Ronen & Matanel Kadosh \n"
            "*/\n\n"
        )
        f1.write("void init_Timer2(void)\n{\n")
        f1.write("   T2CON = 0x00; // Timer2 in auto-reload, timer mode\n")
        f1.write(f"   RCAP2H = 0x{rcap2h:02X};\n")
        f1.write(f"   RCAP2L = 0x{rcap2l:02X};\n")
        f1.write("   TH2 = RCAP2H;\n")
        f1.write("   TL2 = RCAP2L;\n")
        f1.write("   TF2 = 0; // Clear overflow flag- must be cleared by the user\n")
        f1.write("   TR2 = 1; // Turns on Timer2\n")
        f1.write("}\n\n")
        f1.write(
                "void setADC(void)\n{\n"
                "   ADCCON1 = 0XBA; //10111010\n"
                "   CCONV = 1;\n    //The bit from ADDCON2 which respnce on continous conversion \n"
                "   ADCCON2 &= 0XF0; // Set ADC to channel 0\n"
                "\n}\n\n"
                "void setDAC(void)\n{\n"
                "   DACCON = 0X19; //00011011 set bit number 2 to output the value of the 2 DACs"
                "\n}\n\n"
            )
            
    with open("SetTimer2_ADC_DAC.h", "w") as f2:
        f2.write(
        "/* This code generated by setTimer2.py too\n"
            f"   on {datetime.datetime.now()}\n"
            "   An header file for SetTimer2_ADC_DAC.c\n"
            "Name: Matan Ronen & Matanel Kadosh \n"
            "*/\n\n"
            "void init_Timer2(void);\n"
            "void setADC(void);\n"
            "void setDAC(void);\n"
        )
        
if __name__ == '__main__':
    main()

